spring.application.name=back-end


spring.datasource.url=jdbc:mysql://172.21.221.214/cms?usessl=false
spring.datasource.username=root

spring.datasource.password=4Bc0hfLGw6ePfPCR8c11zBOj
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.data.mongodb.uri=mongodb://root:WfY9n2wXuBPX9ewq5UjX3EQA@172.21.83.4:27017/prescriptions?authSource=admin

management.endpoint.health.show-details=always
management.health.db.enabled=true


api.path=/
jwt.secret=$!@#$^%$$$%####$DDCPN0234FCFDPD8670M



spring.web.resources.static-locations=classpath:/static/

# -------------------------
# Thymeleaf Configuration
# -------------------------
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.cache=false    
spring.thymeleaf.encoding=UTF-8

# Logging
debug=true
logging.level.com.project.back_end=DEBUG
logging.level.org.springframework.web=DEBUG